[package]
name = "squeal-sql"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3"
log = "0.4.33"
parking_lot = "0.12.5"
postcard = "1.1.3"
serde = "1.0.228"
sql-parser = {path="../sql-parser"}
store= {path="../store"}
thiserror = "2.0.18"
macros ={path="../macros"}
either = "1.16.0"
uuid = {version="1.24.1", features=["v4"]}
